admin_deliveries_new:
  path: /admin/deliveries/new
  defaults:
      _controller: AppBundle:Admin:newDelivery
      layout: AppBundle::admin.html.twig
      routes:
          stores: admin_stores
          store: admin_store
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_deliveries_calculate_price:
    path:     /admin/deliveries/calculate-price
    defaults: { _controller: AppBundle:Admin:calculateDeliveryPrice }

admin_delivery:
  path: /admin/deliveries/{id}
  defaults:
      _controller: AppBundle:Admin:editDelivery
      layout: AppBundle::admin.html.twig
      routes:
          stores: admin_stores
          store: admin_store
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_order_invoice:
    path:     /admin/orders/{id}.pdf
    defaults: { _controller: AppBundle:Admin:orderInvoice }
    requirements: { id: '\d+' }
    methods:  [ GET ]

admin_orders:
    path:     /admin/orders
    defaults:
        _controller: AppBundle:Admin:orderList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:orders.html.twig
        routes:
            restaurant: admin_restaurant
            order_invoice: admin_order_invoice
    methods:  [ GET ]

admin_restaurant_new:
    path: /admin/restaurants/new
    defaults:
        _controller: AppBundle:Admin:newRestaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu: admin_restaurant_menu
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant:
    path: /admin/restaurants/{id}
    defaults:
        _controller: AppBundle:Admin:restaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu: admin_restaurant_menu
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurants:
    path: /admin/restaurants
    defaults:
        _controller: AppBundle:Admin:restaurantList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:restaurants.html.twig
        routes:
            dashboard: admin_restaurant_dashboard
            menu: admin_restaurant_menu
            restaurant: admin_restaurant
    methods: [ GET ]

admin_restaurant_menu:
    path: /admin/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Admin:restaurantMenu
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: admin_restaurant_menu
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            add_section: admin_restaurant_menu_add_section
    methods: [ GET, POST ]

admin_restaurant_menu_add_section:
    path: /admin/restaurants/{id}/menu/sections
    defaults:
        _controller: AppBundle:Admin:restaurantMenu
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: admin_restaurant_menu
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            add_section: admin_restaurant_menu_add_section
        add_menu_section: true
    methods: [ POST ]

admin_restaurant_planning:
    path: /admin/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Admin:restaurantPlanning
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:planning.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
    methods: [ GET, POST ]

admin_restaurant_dashboard:
    path: /admin/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Admin:restaurantDashboard
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Admin:restaurantDashboardOrder
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order_accept:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Admin:acceptOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_refuse:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Admin:refuseOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_ready:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Admin:readyOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_cancel:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrderFromDashboard
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_orders_order_cancel:
    path: /admin/orders/{id}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrder
        redirect_route: admin_orders
    methods: [ POST ]

admin_stores:
    path: /admin/stores
    defaults:
        _controller: AppBundle:Admin:storeList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:stores.html.twig
        routes:
            store: admin_store
            store_delivery: admin_store_delivery
            store_deliveries: admin_store_deliveries
    methods:  [ GET ]

admin_store_new:
    path: /admin/stores/new
    defaults:
        _controller: AppBundle:Admin:newStore
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
            store_deliveries: admin_store_deliveries
    methods:  [ GET, POST ]

admin_store:
    path: /admin/stores/{id}
    defaults:
        _controller: AppBundle:Admin:store
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
            store_deliveries: admin_store_deliveries
    methods:  [ GET, POST ]

admin_store_delivery:
    path: /admin/stores/{id}/deliveries/new
    defaults:
        _controller: AppBundle:Admin:newStoreDelivery
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store: admin_store
            success: admin_deliveries
            calculate_price: admin_deliveries_calculate_price
    methods:  [ GET, POST ]

admin_store_deliveries:
    path: /admin/stores/{id}/deliveries
    defaults:
        _controller: AppBundle:Admin:storeDeliveries
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store: admin_store
    methods:  [ GET ]

admin_tag_new:
    path: /admin/settings/tags/new
    defaults:
        _controller: AppBundle:Tag:newTag
        template: AppBundle:Admin:tag.html.twig
        redirect_route: admin_tags

admin_tag:
    path: /admin/settings/tags/{slug}
    defaults:
        _controller: AppBundle:Tag:tag
        template: AppBundle:Admin:tag.html.twig
        redirect_route: admin_tags
